# Generated by Django 2.2.7 on 2020-01-18 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0003_auto_20200118_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_generated_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
