# Generated by Django 2.2.7 on 2020-01-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0004_auto_20200118_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_generated_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
