# Generated by Django 2.2.7 on 2020-01-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0006_auto_20200118_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_generated_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='otp time'),
        ),
    ]
