# Generated by Django 3.0.1 on 2020-01-17 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respect', models.CharField(default='', max_length=20)),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('father_first_name', models.CharField(default='', max_length=30)),
                ('father_last_name', models.CharField(default='', max_length=30)),
                ('mother_first_name', models.CharField(default='', max_length=30)),
                ('mother_last_name', models.CharField(default='', max_length=30)),
                ('dob', models.CharField(default='00-00-0000', max_length=20)),
                ('address_line_1', models.TextField(default='', max_length=100)),
                ('address_line_2', models.TextField(default='', max_length=100)),
                ('district', models.CharField(default='', max_length=30)),
                ('pin_code', models.CharField(default='', max_length=20)),
                ('state', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=30)),
                ('phone_no', models.CharField(default='', max_length=10)),
                ('paper_language', models.CharField(default='', max_length=30)),
                ('category_of_teacher', models.CharField(default='', max_length=100)),
                ('orthopedically_or_locomotor_impaired', models.BooleanField(default=False)),
                ('degree_of_disability', models.IntegerField(default=0)),
                ('already_appeared', models.BooleanField(default=False)),
                ('receipt', models.CharField(default='', max_length=100)),
                ('amount', models.FloatField(default=0)),
                ('name_of_bank', models.CharField(default='', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
