# Generated by Django 3.0.1 on 2020-01-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration_form',
            name='address',
        ),
        migrations.AddField(
            model_name='registration_form',
            name='address_line_1',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registration_form',
            name='address_line_2',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registration_form',
            name='already_appeared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration_form',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='registration_form',
            name='category_of_teacher',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registration_form',
            name='degree_of_disability',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registration_form',
            name='district',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='registration_form',
            name='dob',
            field=models.CharField(default='00-00-0000', max_length=20),
        ),
        migrations.AddField(
            model_name='registration_form',
            name='father_first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='registration_form',
            name='father_last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='registration_form',
            name='mother_first_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='registration_form',
            name='mother_last_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='registration_form',
            name='name_of_bank',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registration_form',
            name='orthopedically_or_locomotor_impaired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration_form',
            name='paper_language',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='registration_form',
            name='phone_no',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='registration_form',
            name='receipt',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registration_form',
            name='respect',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='registration_form',
            name='state',
            field=models.CharField(default='', max_length=30),
        ),
    ]
