# Generated by Django 3.0.1 on 2020-01-18 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration_form',
            old_name='district',
            new_name='city',
        ),
    ]
